apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Exposed port on the node
