apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ASPNETCORE_ENVIRONMENT
            - name: DatabaseOptions__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DatabaseOptions__ConnectionString